title: "Surendrakumar Deshpande"
description: "Platform DevOps Engineer | Kubernetes | AWS | CI/CD | Platform Engineering"
baseurl: ""
url: "https://surendra-deshpande.github.io"
theme: minima

author:
  name: "Surendrakumar Deshpande"
  email: "surendrakumardeshpande@gmail.com"

# Social links
linkedin_username: surendrakumardeshpande
github_username: surendra-deshpande

# Build settings
markdown: kramdown
