title: "Surendrakumar Deshpande"
email: "surendrakumardeshpande@gmail.com"
description: "Platform DevOps Engineer | Kubernetes | Cloud | CI/CD | Platform Engineering"
github_username: surendra-deshpande
linkedin_username: surendrakumardeshpande
theme: minima
markdown: kramdown